#!/bin/bash

set -e

cd "${1}"

exec 3>&1
exec 1>&2
set +x

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-out.XXXXXX)

cat > "${payload}" <&0

sonar_host_url=$(jq -r '.source.host_url // ""' < "${payload}")
if [ -z "${sonar_host_url}" ]; then
  echo "host_url param has not been specified."
  exit 1
fi

sonar_login=$(jq -r '.source.login // ""' < "${payload}")
if [ -z "${sonar_login}" ]; then
  echo "login param has not been specified."
  exit 1
fi

analysis_id=$(jq -r '.version.analysis_id // ""' < "${payload}")
if [ -z "${analysis_id}" ]; then
  echo "no analysis id."
  exit 1
fi

curl -s -u "${sonar_login}:" -L -o sonar-qualitygates-status.json "${sonar_host_url}/api/qualitygates/project_status?analysisId=${analysis_id}"

qualitygates_status=$(jq -r '.projectStatus.status' < "sonar-qualitygates-status.json")

jq -n "{
  version: { \"analysis_id\": \"${analysis_id}\" },
  metadata: [
    { name: \"qualitygates_status\", value: \"${qualitygates_status:?}\" }
  ]
}" >&3
