#!/bin/bash

set -e

cd "${1}"

exec 3>&1
exec 1>&2
set +x

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-out.XXXXXX)

cat > "${payload}" <&0

sonar_host_url=$(jq -r '.source.host_url // ""' < "${payload}")
if [ -z "${sonar_host_url}" ]; then
  echo "host_url param has not been specified."
  exit 1
fi

sonar_login=$(jq -r '.source.login // ""' < "${payload}")
if [ -z "${sonar_login}" ]; then
  echo "sonar_login param has not been specified."
  exit 1
fi

sonar_project_key=$(jq -r '.params.project_key // ""' < "${payload}")
if [ -z "${sonar_project_key}" ]; then
  echo "project_key param has not been specified."
  exit 1
fi

sonar_project_name=$(jq -r '.params.project_name // ""' < "${payload}")
if [ -z "${sonar_project_name}" ]; then
  echo "project_name param has not been specified."
  exit 1
fi

version_val=""
version=$(jq -r '.params.version // ""' < "${payload}")
if [ -n "${version}" ]; then
  version_val=$(cat $version)
fi

source=$(jq -r '.params.source // ""' < "${payload}")
if [ -z "${source}" ]; then
  echo "source param has not been specified."
  exit 1
fi

projects=$(jq -r '.params.projects // ""' < "${payload}")
if [ -z "${projects}" ]; then
  projects=$(for f in $source/**/*.csproj; do dirname $f; done)
fi

options=""
extraParams=$(jq -r '.params.extra_params[] // ""' < "${payload}")
for ep in $extraParams; do options+="/d:$ep "; done

mono /opt/sonar-scanner-msbuild/SonarQube.Scanner.MSBuild.exe begin /d:sonar.host.url=$sonar_host_url /d:sonar.login=$sonar_login /k:$sonar_project_key /n:"$sonar_project_name" /v:$version_val $options
for p in $projects; do dotnet restore $p; done
for p in $projects; do dotnet build $p; done
mono /opt/sonar-scanner-msbuild/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$sonar_login

analysis_id=$(curl -u "${sonar_login}:" -s -L "${sonar_host_url}/api/ce/activity?q=${sonar_project_key}&onlyCurrents=true" | jq -r .tasks[0].analysisId)

jq -n "{
  version: { \"analysis_id\": \"${analysis_id}\" },
  metadata: [
    { name: \"project_key\", value: \"${sonar_project_key:?}\" }
  ]
}" >&3
